config/routes.rb
Tibdirectory::Application.routes.draw do
  root 'listings#index'
  resources :listings
  resources :categories, only: [:new, :create]
  resources :users, only: [:new, :create]

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :listing_categories
  has_many :listings, through: :listing_categories

  validates :name, presence: true
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_many :listing_categories
  has_many :categories, through: :listing_categories

  validates :name, presence: true
end

app/models/listing_category.rb
class ListingCategory < ActiveRecord::Base
	belongs_to :listing
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	def admin?
		self.role.to_s == 'admin'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?


  def current_user
  	@current_user ||= User.find(session[:user_id])if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	unless logged_in?
  		flash[:error] = "Please login to do that"
  		redirect_to login_path
  	end
  end

  def require_admin
  	access_denied unless logged_in? and current_user.admin?
  end

  def access_denied
  	flash[:error] =  "Sorry, only the admin can do that"
  	redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, only: [:new, :create]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = 'Category Created'
      redirect_to listings_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find_by(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :require_admin, except: [:index, :show]


	def index
		@listings = Listing.all
	end
	def new  
		@listing = Listing.new
	end

	def create
		@listing = Listing.new(listing_params)

		if @listing.save
			flash[:notice] = "listing save"
			redirect_to listings_path
		else
			flash[:error] = "something went wrong"
			render 'new'
		end
	end

	def edit
		@listing = Listing.find(params[:id])
	end

	def update
		@listing = Listing.find(params[:id])

		if @listing.update(listing_params)
			flash[:notice] = "listing save"
			redirect_to listings_path
		else
			flash[:error] = "something went wrong"
			render 'edit'
		end
	end

	def destroy
		@listing = Listing.find(params[:id])
		@listing.destroy
		flash[:notice] = "listing destroyed"
		redirect_to root_path
	end

	private

	def listing_params
		params.require(:listing).permit(:name, :address, :city, :phone, :website, :image, category_ids: [])
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(username: params[:username])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id 
			flash[:notice] = "You have logged in"
			redirect_to root_path
		else
			flash[:error] = "Access Denied"
			redirect_to root_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:error] = "You have logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_admin
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			flash[:notice] = "User created"
			redirect_to listings_path
		else
			flash[:error] = "There were some problems"
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<br><br>
<div align="center">
	<%= form_for @category do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name%>
	<%= f.submit %>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<p class="info">Developed with love by <a href="http://www.vajradog.com/">@vajradog</a></p>

app/views/layouts/_navigation.html.erb
<div class="container">

<% if logged_in? %>
<header class="clearfix">
	<%= link_to 'New Listing', new_listing_path%> | 
	<%= link_to 'Log out', logout_path %>
</header>
<% end %>
<!--<header class="clearfix">
	<#%= image_tag "logo.png", class: "logo"%>
	<nav>
		<a href="http://youngtibet.com" data-info="Blueprint"><span>Young Tibet </span></a>
	</nav> 
</header>	-->
<div id="tabs" class="tabs">
	<nav>
		<ul>
			<li><a href="#section-1" class="icon-office"><span>NGOs</span></a></li>
			<li><a href="#section-2" class="icon-restaurant"><span>Restaurants</span></a></li>
			<li><a href="#section-3" class="icon-shops"><span>Shops</span></a></li>
			<li><a href="#section-4" class="icon-globe"><span>Intepreters</span></a></li>
			<li><a href="#section-5" class="icon-about"><span>About</span></a></li>
		</ul>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tibetan Listings</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0;">

</head>
<body>
<%= render 'layouts/navigation'%>
<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: name %>
<% end -%>

<%= yield %>
<%= render 'layouts/footer'%>
</body>
<script>
	new CBPFWTabs( document.getElementById( 'tabs' ) );
</script>
		
</html>

app/views/listings/_about.html.erb
<div class="aboutbox">
	<h3>About</h3>
	<p>This website is a single-page application built with Ruby on Rails by <a href="https://github.com/vajradog">Thupten N. Chakrishar <i>aka vajradog</i></a>. Currently only the admin can login and add/edit or delete a listing. If you want to build a similar application, <a href="https://github.com/vajradog/tibetanlistings">click here for the source code.</a> <br><br>
	The website design credit goes to the wonderful Mary Lou (Manoela Ilic). You can find the source code <a href="https://github.com/codrops/FullWidthTabs">here</a>. <br><br>
	<strong>Road map for the site:</strong>
	
	<ul>
		<li>User listing submission and admin approval system <i>(I may do Facebook authentication and then authorisation).</i></li>
		<li>Reporting mistakes in the listings</li>
		<li>Search Functionality</li>
		<li>Integrate Google Maps</li>
		<li>Expand listing outside NYC</li>
		<li>Perhaps a show page with more information about the listing</li>
	</ul>
	</p>
</div>	

app/views/listings/_form.html.erb
<%= form_for @listing do |form| %>
<%= form.label :name %>
<%= form.text_field :name %><br>
<%= form.label :address %>
<%= form.text_field :address %><br>
<%= form.label :city %>
<%= form.text_field :city %><br>
<%= form.label :phone %>
<%= form.text_field :phone %><br>
<%= form.label :website %>
<%= form.text_field :website %><br>
<%= form.label :image %>
<%= form.text_field :image %><br>
  <br>

 <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <%= cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text}%>
  <% end %>
<!--
<#%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
 
 second line is just styling, the first line works fine. Check http://apidock.com/rails/v4.0.2/ActionView/Helpers/FormOptionsHelper/collection_check_boxes -->
    <br>
<%= form.submit(@listing.new_record? ? "create listing" : "Update listing" )%>
  <% end %>

app/views/listings/_listing.html.erb
<div class="mediabox">
	<% if list.image? %>
		<img src="<%= list.image %>" alt="offices" />
	<% else %>
		<img src="https://dl.dropbox.com/s/60cgildnnrbgop7/default.jpg" alt="offices" />
	<% end %>
	
	<% if list.website? %>
		<h3><%= link_to ("#{list.name}" '*'), list.website, target: "_blank" %></h3>
	<% else %>
		<h3><%= list.name %></h3>
	<% end %>

	<% if logged_in? %>
	<strong><%= link_to 'Edit', edit_listing_path(list)%> | <%= link_to 'Delete', list, confirm: 'Are you sure?', method: :delete%></strong>
	<% end %>
	
	<p>
		<% if list.address? %>
			<%= list.address %>
		<% else %>
			<small><i>Address not available</i></small>
		<% end %> <br>
		
		<%= list.city %><br>
	
	<% if list.phone? %>
		<%= list.phone %>
	<% else %>
		<small><i>Phone not available</i></small>
	<% end %>
	</p>	
</div>

app/views/listings/edit.html.erb
<%= render 'form' %>

app/views/listings/index.html.erb
<div class="content">
	<section id="section-1">
		<% Category.first.listings.all.each do |list| %>
			<%= render 'listing', list: list%>
		<% end %>
	</section>

	<section id="section-2">
		<% Category.find(2).listings.all.each do |list| %>
			<%= render 'listing', list: list%>
		<% end %>
	</section>

	<section id="section-3">
		<% Category.find(3).listings.all.each do |list| %>
			<%= render 'listing', list: list%>
		<% end %>
	</section>

	<section id="section-4">
		<% Category.find(4).listings.all.each do |list| %>
			<%= render 'listing', list: list%>
		<% end %>
	</section>

	<section id="section-5">
		<%= render 'about'%>
	</section>
</div>

app/views/listings/new.html.erb
<br><br>
<div align="center">
	<%= render 'form'%>
</div></div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %> <br>
<%= f.label :password %>
<%= f.password_field :password %> <br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br>
<%= f.submit %>
<% end %>